export interface Playlist {
  id: number;
  title: string;
  color: string;
  cover: string;
  artists: string[];
}

export const playlists: Playlist[] = [
  {
    id: 1,
    title: 'Chill Lo-Fi Music',
    color: '#60371a',
    cover: '/covers/VINYL_MORNING_COFFEE_4-min.webp',
    artists: ['NoSpirit', 'Casiio'],
  },
  {
    id: 2,
    title: 'Lo-Fi Chill Session',
    color: '#86c7f8',
    cover: '/covers/2amsynth-vinyl.webp',
    artists: ['Kupla', 'Blue Fox'],
  },
  {
    id: 3,
    title: 'Study Session',
    color: '#ed2377',
    cover: '/covers/a1435058381_65.webp',
    artists: ['Tenno', 'xander', 'Team Astro'],
  },
  {
    id: 4,
    title: 'Blue Note Study Time',
    color: '#1e3a8a',
    cover: '/covers/a1962013209_16.webp',
    artists: ['Raimu', 'Yasumu'],
  },
  {
    id: 5,
    title: 'Chau Saura Session',
    color: '#df24ff',
    cover: '/covers/a2793859494_16.webp',
    artists: ['Chau Saura', 'amies', 'kyu'],
  },
  {
    id: 6,
    title: 'Like a Necessity',
    color: '#cc5400',
    cover: '/covers/a0363730459_16.webp',
    artists: ['WFS', 'Nadav Cohen'],
  },
  {
    id: 7,
    title: 'Chill Vibes',
    color: '#f2776f',
    cover: '/covers/edrgdfgfdgdfgd.webp',
    artists: ['Andrew Drake', 'Juan Magan', "Pitbull"],
  },
  {
    id: 8,
    title: 'Soothing Sounds',
    color: '#308f8d',
    cover: '/covers/556ur3tdfterte.webp',
    artists: ['John Swarn', 'Natalia Mconan'],
  },
];

export interface Song {
  id: number;
  playlistId: number;
  title: string;
  image: string;
  artists: string[];
  album: string;
  duration: string;
}

export const songs: Song[] = [
  {
    id: 1,
    playlistId: 1,
    title: 'Moonlit Walk',
    image: '/covers/VINYL_MORNING_COFFEE_4-min.webp',
    artists: ['LoFi Dreamer', 'LoFi Lover'],
    album: 'Chill Lo-Fi Music',
    duration: '3:12',
  },
  {
    id: 2,
    playlistId: 1,
    title: 'Coffee Daze',
    image: '/covers/VINYL_MORNING_COFFEE_4-min.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '4:07',
  },
  {
    id: 3,
    playlistId: 1,
    title: 'Skyline Serenade',
    image: '/covers/VINYL_MORNING_COFFEE_4-min.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '3:50',
  },
  {
    id: 4,
    playlistId: 1,
    title: 'Urban Echoes',
    image: '/covers/VINYL_MORNING_COFFEE_4-min.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '3:30',
  },
  {
    id: 5,
    playlistId: 1,
    title: "Night's End",
    image: '/covers/VINYL_MORNING_COFFEE_4-min.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '4:20',
  },
  {
    id: 1,
    playlistId: 2,
    title: 'Silent Rain',
    image: '/covers/2amsynth-vinyl.webp',
    artists: ['Urban Nocturne'],
    album: 'Midnight Tales',
    duration: '3:40',
  },
  {
    id: 2,
    playlistId: 2,
    title: 'Lost Pages',
    image: '/covers/2amsynth-vinyl.webp',
    artists: ['Urban Nocturne'],
    album: 'Midnight Tales',
    duration: '3:20',
  },
  {
    id: 3,
    playlistId: 2,
    title: 'Midnight Tales',
    image: '/covers/2amsynth-vinyl.webp',
    artists: ['Urban Nocturne'],
    album: 'Midnight Tales',
    duration: '3:50',
  },
  {
    id: 4,
    playlistId: 2,
    title: 'City Lights',
    image: '/covers/2amsynth-vinyl.webp',
    artists: ['Urban Nocturne'],
    album: 'Midnight Tales',
    duration: '3:30',
  },
  {
    id: 5,
    playlistId: 2,
    title: 'Night Drive',
    image: '/covers/2amsynth-vinyl.webp',
    artists: ['Urban Nocturne'],
    album: 'Midnight Tales',
    duration: '4:20',
  },
  {
    id: 1,
    playlistId: 3,
    title: 'Lunar',
    image: '/covers/a1435058381_65.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '3:40',
  },
  {
    id: 2,
    playlistId: 3,
    title: 'Go go go!',
    image: '/covers/a1435058381_65.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '3:20',
  },
  {
    id: 3,
    playlistId: 3,
    title: 'Keep focus!',
    image: '/covers/a1435058381_65.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '2:40',
  },
  {
    id: 4,
    playlistId: 3,
    title: 'JavaScript is the way',
    image: '/covers/a1435058381_65.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '3:10',
  },
  {
    id: 5,
    playlistId: 3,
    title: 'No more TypeScript for me',
    image: '/covers/a1435058381_65.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '2:10',
  },
  {
    id: 1,
    playlistId: 4,
    title: 'Lunar',
    image: '/covers/a1962013209_16.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '3:40',
  },
  {
    id: 2,
    playlistId: 4,
    title: 'Go go go!',
    image: '/covers/a1962013209_16.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '3:20',
  },
  {
    id: 3,
    playlistId: 4,
    title: 'Keep focus!',
    image: '/covers/a1962013209_16.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '2:40',
  },
  {
    id: 4,
    playlistId: 4,
    title: 'JavaScript is the way',
    image: '/covers/a1962013209_16.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '3:10',
  },
  {
    id: 5,
    playlistId: 4,
    title: 'No more TypeScript for me',
    image: '/covers/a1962013209_16.webp',
    artists: ['Tenno'],
    album: 'Study Session',
    duration: '2:10',
  },
  {
    id: 1,
    playlistId: 5,
    title: 'Moonlit Walk',
    image: '/covers/a2793859494_16.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '3:12',
  },
  {
    id: 2,
    playlistId: 5,
    title: 'Coffee Daze',
    image: '/covers/a2793859494_16.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '4:07',
  },
  {
    id: 3,
    playlistId: 5,
    title: 'Skyline Serenade',
    image: '/covers/a2793859494_16.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '3:50',
  },
  {
    id: 4,
    playlistId: 5,
    title: 'Urban Echoes',
    image: '/covers/a2793859494_16.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '3:30',
  },
  {
    id: 5,
    playlistId: 5,
    title: "Night's End",
    image: '/covers/a2793859494_16.webp',
    artists: ['LoFi Dreamer'],
    album: 'Chill Lo-Fi Music',
    duration: '4:20',
  },

  {
    id: 1,
    playlistId: 6,
    title: 'Moonlit Walk',
    image: '/covers/a0363730459_16.webp',
    artists: ['Nadav Cohen'],
    album: 'Like a Necessity',
    duration: '1:57',
  },
  {
    id: 2,
    playlistId: 6,
    title: 'Coffee Daze',
    image: '/covers/a0363730459_16.webp',
    artists: ['Nadav Cohen'],
    album: 'Like a Necessity',
    duration: '1:49',
  },
  {
    id: 3,
    playlistId: 6,
    title: 'Skyline Serenade',
    image: '/covers/a0363730459_16.webp',
    artists: ['WFS', 'Nadav Cohen'],
    album: 'Like a Necessity',
    duration: '2:35',
  },
  {
    id: 4,
    playlistId: 6,
    title: 'Urban Echoes',
    image: '/covers/a0363730459_16.webp',
    artists: ['WFS'],
    album: 'Like a Necessity',
    duration: '2:49',
  },
  {
    id: 5,
    playlistId: 6,
    title: "Night's End",
    image: '/covers/a0363730459_16.webp',
    artists: ['WFS', 'Nadav Cohen'],
    album: 'Like a Necessity',
    duration: '2:29',
  },

  {
    id: 1,
    playlistId: 7,
    title: "Aquario on the beach",
    image: '/covers/edrgdfgfdgdfgd.webp',
    artists: ['Andrew Drake', 'Juan Magan', "Pitbull"],
    album: 'Chill Vibes',
    duration: '3:01',
  },
  {
    id: 2,
    playlistId: 7,
    title: "Love Is All Around",
    image: '/covers/edrgdfgfdgdfgd.webp',
    artists: ['Andrew Drake', 'Juan Magan', "Pitbull"],
    album: 'Chill Vibes',
    duration: '3:17',
  },
  {
    id: 3,
    playlistId: 7,
    title: "Solitude",
    image: '/covers/edrgdfgfdgdfgd.webp',
    artists: ['Andrew Drake', 'Juan Magan', "Pitbull"],
    album: 'Chill Vibes',
    duration: '2:02',
  },
  {
    id: 4,
    playlistId: 7,
    title: "Dreamin'",
    image: '/covers/edrgdfgfdgdfgd.webp',
    artists: ['Andrew Drake', 'Juan Magan', "Pitbull"],
    album: 'Chill Vibes',
    duration: '2:24',
  },
  {
    id: 5,
    playlistId: 7,
    title: "Sailing to Antigua & Barbuda",
    image: '/covers/edrgdfgfdgdfgd.webp',
    artists: ['Andrew Drake', 'Juan Magan', "Pitbull"],
    album: 'Chill Vibes',
    duration: '1:32',
  },

  {
    id: 1,
    playlistId: 8,
    title: "Childhood",
    image: '/covers/556ur3tdfterte.webp',
    artists: ['John Swarn', 'Natalia Mconan'],
    album: 'Soothing Sounds',
    duration: '1:50',
  },
  {
    id: 2,
    playlistId: 8,
    title: "Girls I Loved",
    image: '/covers/556ur3tdfterte.webp',
    artists: ['John Swarn', 'Natalia Mconan'],
    album: 'Soothing Sounds',
    duration: '1:51',
  },
  {
    id: 3,
    playlistId: 8,
    title: "I Love The Night",
    image: '/covers/556ur3tdfterte.webp',
    artists: ['John Swarn', 'Natalia Mconan'],
    album: 'Soothing Sounds',
    duration: '2:24',
  },
  {
    id: 4,
    playlistId: 8,
    title: "Sweet Medicine",
    image: '/covers/556ur3tdfterte.webp',
    artists: ['John Swarn', 'Natalia Mconan'],
    album: 'Soothing Sounds',
    duration: '2:03',
  },
  {
    id: 5,
    playlistId: 8,
    title: "Winter Days",
    image: '/covers/556ur3tdfterte.webp',
    artists: ['John Swarn', 'Natalia Mconan'],
    album: 'Soothing Sounds',
    duration: '2:43',
  },
  {
    id: 6,
    playlistId: 8,
    title: "Aftermath",
    image: '/covers/556ur3tdfterte.webp',
    artists: ['John Swarn', 'Natalia Mconan'],
    album: 'Soothing Sounds',
    duration: '2:46',
  },
];
